# -*- coding: utf-8 -*-
"""DL_Lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sCA8-kJYJUnyw0qaKcrT2y0aHZ4mXxJ3
"""

#from google.colab import drive
#drive.mount('/content/drive')
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import cv2
import numpy as np
from skimage.io import imread_collection
col_dir1='/content/drive/My Drive/Colab Notebooks/Trump/*.jpg'
col_dir2='/content/drive/My Drive/Colab Notebooks/chicken/*.jpg'
trump=imread_collection(col_dir1)
chicken=imread_collection(col_dir2)
trump_pixels=[]
chicken_pixels=[]
for i in range(0,10):
  trump_pixels=cv2.resize(trump[i],(50,50))
for i in range(0,10):
  chicken_pixels=cv2.resize(chicken[i],(50,50))
X=trump_pixels+chicken_pixels
X=X.flatten().reshape(20,375)
#print(X)
y=[]
for i in range(20):
  if(i<10):
    y.append(1)
  else:
    y.append(0)

import pandas as pd
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

logreg = LogisticRegression()
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, y_test)))

